server:
  port: 8081
spring:
  application:
    name: restful-api-demo
  profiles:
    include: dao,dubbo,redis-base



#swagger 配置
swagger: 
  title: API示例
  desc: 基于springBoot编写的RESful-API
  version: 0.0.1.SNAPSHOT
  termsOfServiceUrl: javascript:void(0)
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  basePackage: com.tyu.web
  groupName: 默认API示例分组
  contactName: crossoverFish
#  contactUrl: https://github.com/crossoverFish-dev/restful-api-demo.git
  contactEmail: 495457022@qq.com


