dubbo:
  application:
    name: crossover-core
    environment: develop
  protocol:
    port: 30001
    threadpool: fixed
    threads: 200
    dispatcher: message
  registry:
    address: 10.20.16.74:2188
    file: dubbo-registry-cache/crossover-core{replicas.id:}.cache
  provider:
    timeout: 60000
    connections: 5
    group: prodGroup
    version: 1.0.0
    retries: 0
  consumer:
    check: false
    group: prodGroup
  others:
    goods-center:
      group: TESTPCC
      version: 1.0.0
    order-center:
      group: DEVNOC
      version: 1.0.0

---

spring:
  profiles: test

dubbo:
  registry:
    address: 10.125.131.116:2181,10.125.131.116:2182,10.125.131.116:2183
  provider:
    group: yxsmGroup
  consumer:
    group: yxsmGroup

---

spring:
  profiles: prod

dubbo:
  registry:
    address: 192.168.0.5:2181,192.168.0.6:2181,192.168.0.7:2181
  provider:
    group: yxsmGroup
  consumer:
    group: yxsmGroup
  others:
    goods-center:
      group: PRODPCC
      version: 1.0.0
    order-center:
      group: PRODNOC
      version: 1.0.0

---

spring:
  profiles: local

dubbo:
  registry:
    address: 127.0.0.1:2181

---

spring:
  profiles: dev

dubbo:
  registry:
    address: 10.20.16.74:2188