spring:
  application:
    name: crossover-core
  profiles:
    include: dao,dubbo,redis-base,datasource


logging:
  level:
    root: info
    com.tyu: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
  config: classpath:config/logback-spring.xml





