spring:
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 #连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
        max-wait: 1000  #连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 20000
    database: 0
    password: 123456



